apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-config
data:
  zk_endpoint: "zk-cs:2181"
  cluster_name: "/falcon"
  STORAGE_THRESHOLD: "0.9"
  BRPC_PORT: "50039"
  wait_replica_time: "600"
  data_dir: "/home/falconMeta/data"
  cn_num: "3"
  cn_sup_num: "0" #number of cn supplement
  # (dn_num - dn_sup_num) / 3 is the number of primary dn in our cluster
  dn_num: "4" #number of total dn pod
  dn_sup_num: "1" #number of dn supplement
